huh:
  encore:
    entries:
      - {
          name: "contao-formhybrid-compatibility-bundle",
          file: 'vendor/heimrichhannot/contao-formhybrid-compatibility-bundle/src/Resources/assets/js/contao-formhybrid-compatibility-bundle.js',
          requiresCss: false
        }
    legacy:
      js:
        - jquery.formhybrid