huh:
  encore:
    entries:
      - { name: "contao-formhybrid-compatibility-bundle", file: 'vendor/heimrichhannot/contao-formhybrid-compatibility-bundle/src/Resources/assets/js/contaoFormhybridCompatibilityBundle.es6.js', requiresCss: false }
    legacy:
      js:
        - jquery.formhybrid