services:
  _defaults:
    autowire: true

  HeimrichHannot\ContaoFormhybridCompatibilityBundle\Asset\FrontendAsset:
    calls:
      - [setEncoreFrontendAsset, ['@?HeimrichHannot\EncoreBundle\Asset\FrontendAsset']]

  HeimrichHannot\ContaoFormhybridCompatibilityBundle\EventListener\FormhybridOnCreateInstanceListener:
    public: true