services:
  _defaults:
    autowire: true

  HeimrichHannot\FormhybridCompatibilityBundle\Asset\FrontendAsset:
    calls:
      - [setEncoreFrontendAsset, ['@?HeimrichHannot\EncoreBundle\Asset\FrontendAsset']]

  HeimrichHannot\FormhybridCompatibilityBundle\EventListener\:
    resource: '../../EventListener/*'
    autoconfigure: true