huh_encore:
  js_entries:
    - {
        name: "contao-formhybrid-compatibility-bundle",
        file: 'vendor/heimrichhannot/contao-formhybrid-compatibility-bundle/assets/js/contao-formhybrid-compatibility-bundle.js',
        requires_css: false
      }
  unset_global_keys:
    js:
      - jquery.formhybrid